#!/bin/bash
#

USER_AUTOSTART="/home/assem/.scripts/autostart.sh"

if [ -f $USER_AUTOSTART ]
then
    bash $USER_AUTOSTART &
fi

# Update Dbus Environment
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots

# XDG portals for screen share
for portal in xdg-desktop-portal-gtk xdg-desktop-portal-wlr xdg-desktop-portal; do
   pkill -e "$portal"
done

# Start xdg-desktop-portal-wlr and xdg-desktop-portal-gtk
/usr/libexec/xdg-desktop-portal-wlr &
/usr/libexec/xdg-desktop-portal-gtk &

sleep 1

# Start main xdg-desktop-portal
/usr/libexec/xdg-desktop-portal &
